export const employees = [
    {
        id: 1001,
        name: 'Abraham Matthews',
        email: 'amatthe@company.com',
        phone: '123-456-7890',
        position: 'CEO',
    },
    {
        id: 1002,
        name: 'Bethany Jones',
        email: 'bjones@company.com',
        phone: '123-456-7890',
        position: 'Head of staff/HR',
        reportsTo: 1001,
    },
    {
        id: 1003,
        name: 'Cindy Smith',
        email: 'csmith@company.com',
        phone: '123-456-7890',
        position: 'Head of engineering',
        reportsTo: 1001,
    },
    {
        id: 1004,
        name: 'Dorothy Taylor',
        email: 'dtaylor@company.com',
        phone: '123-456-7890',
        position: 'Head of design',
        reportsTo: 1001,
    },
    {
        id: 1005,
        name: 'Eugene Williams',
        email: 'ewillia@company.com',
        phone: '123-456-7890',
        position: 'Team Leader',
        reportsTo: 1002,
    },
    {
        id: 1006,
        name: 'Fernando Gonzalez',
        email: 'fgonzal@company.com',
        phone: '123-456-7890',
        position: 'Team Leader',
        reportsTo: 1002,
    },
    {
        id: 1007,
        name: 'Geraldine Martinez',
        email: 'gmartin@company.com',
        phone: '123-456-7890',
        position: 'Team Leader',
        reportsTo: 1003,
    },
    {
        id: 1008,
        name: 'Helen Edwards',
        email: 'hedward@company.com',
        phone: '123-456-7890',
        position: 'Engineer',
        reportsTo: 1007,
    },
    {
        id: 1009,
        name: 'Irene Phillips',
        email: 'iphilli@company.com',
        phone: '123-456-7890',
        position: '',
        reportsTo: '',
    },
    {
        id: 1010,
        name: 'Jennifer Jones',
        email: 'jjones@company.com',
        phone: '123-456-7890',
        position: '',
        reportsTo: '',
    },
    {
        id: 1011,
        name: 'Karen Davis',
        email: 'kdavis@company.com',
        phone: '123-456-7890',
        position: 'Team Leader',
        reportsTo: 1004,
    },
    {
        id: 1012,
        name: 'Linda Smith',
        email: 'lsmith@company.com',
        phone: '123-456-7890',
        position: 'Designer',
        reportsTo: 1011,
    },
];